### ISSUE TITLE
PostgreSQL database driver (node-postgres) v7.x not supported

### ISSUE THREAD

**Issue by lfurzewaddock** [boylesoftware/x2node-dbos#5]
Following the [x2node tutorial](http://x2node.com/tutorial/), after running npm start for the first time and visiting the /products endpoint to test the web-service, the following error occurs. 

Downgrading npm package: 'pg' to v6.4.2 resolves the problem. 

```
2017-09-07T21:05:13.797Z 1883 ERROR: error executing SQL [SELECT z.id AS "id", z.name AS "name", z.description AS "description", z.price AS "price", z.is_available AS "available" FROM products AS z]
TypeError: query.on is not a function
    at PostgreSQLDBDriver.executeQuery (/mnt/d/Users/User1/Projects/Dev/x2node-tutorial/node_modules/x2node-dbos/lib/driver/pg-driver.js:361:9)
    at Promise (/mnt/d/Users/User1/Projects/Dev/x2node-tutorial/node_modules/x2node-dbos/lib/fetch-dbo.js:54:19)
    at Promise (<anonymous>)
    at promiseChain.then (/mnt/d/Users/User1/Projects/Dev/x2node-tutorial/node_modules/x2node-dbos/lib/fetch-dbo.js:49:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2017-09-07T21:05:13.910Z 1883 ERROR: internal server error
TypeError: query.on is not a function
    at PostgreSQLDBDriver.executeQuery (/mnt/d/Users/User1/Projects/Dev/x2node-tutorial/node_modules/x2node-dbos/lib/driver/pg-driver.js:361:9)
    at Promise (/mnt/d/Users/User1/Projects/Dev/x2node-tutorial/node_modules/x2node-dbos/lib/fetch-dbo.js:54:19)
    at Promise (<anonymous>)
    at promiseChain.then (/mnt/d/Users/User1/Projects/Dev/x2node-tutorial/node_modules/x2node-dbos/lib/fetch-dbo.js:49:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by levahim** [comment]
Brian introduced some substantial breaking API changes in version 7. Good catch, we'll make the adjustments. Currently the debate is whether to make a new DBO driver "pg7" or try to implement support for all versions in the standard "pg" driver. Either way, will be fixed soon...

**Comment by levahim** [comment]
Fixed. The built-in pg driver now supports both versions 6 and 7.
